### ISSUE TITLE
the git graph has a empty line with a single empty character at the end of the buffer

### ISSUE THREAD

**Issue by 231tr0n** [rbong/vim-flog#132] opened 2024-07-28 18:29 UTC
Hi! Thank you for this wonderful plugin. I really like the graph a lot. Upon using it I came across this extra line at the end with a extra character. Altough it is not that big of an issue, my editor marks eol and empty line with space characters with red color. Hence wanted to see if something could be done about removing this extra line.
![image](https://github.com/user-attachments/assets/d827bbce-06c7-44b4-a007-4b6a29b0a8a9)

**Comment by rbong** [comment] 2024-09-02 17:28
There should be no more line with a space at the end on master.

Although now there are spaces at the end of merge branch lines for optimization reasons. If you have problems with these, please let me know. Please post your `init.lua` or `.vimrc` if this is a problem because it's not built-in to Vim and must be  part of a plugin.

**Comment by 231tr0n** [comment] 2024-09-02 17:44
> There should be no more line with a space at the end on master.
> 
> Although now there are spaces at the end of merge branch lines for optimization reasons. If you have problems with these, please let me know. Please post your `init.lua` or `.vimrc` if this is a problem because it's not built-in to Vim and must be part of a plugin.

Yeah it is part of my colorscheme and mini.trailspace plugin most probably.

**Comment by 231tr0n** [comment] 2024-09-02 17:48
![image](https://github.com/user-attachments/assets/dbcb8392-e93c-44c8-92a8-715d7d18e126)
@rbong currently the git graph looks like this. Is there a way to remove trailing spaces.

**Comment by 231tr0n** [comment] 2024-09-02 17:50
I mean I can remove those highlights myself on buftype flot-* so that it does not appear anymore but wanted to know if something could be done by the plugin itself. Is this possible in anyway.

**Comment by rbong** [comment] 2024-09-02 18:51
It's technically possible but not without a lot of effort and probably branch drawing bugs to handle special cases, so I would rather not.
The change that resulted in this was made because it allows a 1.5x speed improvement and cleaner code.
I would also not like to add a general highlight group to try and override this in all cases. Syntax-based highlighting is slow enough already and this won't catch everything.

The best option is to disable your trailing whitespace plugins in the Flog buffer, or to add your own highlight group if your plugin doesn't provide an option.

Apologies, but cleaner and faster code is a priority.
I do want to remove trailing whitespace for aesthetic reasons but I'm not touching the branch drawing algorithm again for a while.

I've added `let b:minitrailspace_disable = true` to the Flog buffer in [v3](https://github.com/rbong/vim-flog/pull/125).
However according to the mini.trailspace documentation, it should already be disabled in non-modifiable buffers by default, so it may actually be a mini.trailspace bug if this fixes it.

I couldn't find anything in tokyonight that highlights trailing whitespace after a quick look.

**Comment by 231tr0n** [comment] 2024-09-02 19:05
> It's technically possible but not without a lot of effort and probably branch drawing bugs in special cases, so I would rather not. The change that resulted in this was made because it allows a 1.5x speed improvement and cleaner code. I would also not like to add a general highlight group to try and override this in all cases. Syntax-based highlighting is slow enough already and this won't catch everything.
> 
> The best option is to disable your trailing whitespace plugins in the Flog buffer, or to add your own highlight group if your plugin doesn't provide an option.
> 
> Apologies, but cleaner and faster code is a priority. I do want to remove trailing whitespace for aesthetic reasons but I'm not touching the branch drawing algorithm again for a while.
> 
> I've added `let b:minitrailspace_disable = true` to the Flog buffer in [v3](https://github.com/rbong/vim-flog/pull/125). However according to the mini.trailspace documentation, it should already be disabled in non-modifiable buffers by default, so it may actually be a mini.trailspace bug if this fixes it.
> 
> I couldn't find anything in tokyonight that highlights trailing whitespace after a quick look.

@rbong i just found out that the trailspace highlight is due to this highlight group from mini.trailspace ``MiniTrailspace``. This is being highlighted by tokyonight.nvim in the manner as shown in the screenshot.
![image](https://github.com/user-attachments/assets/47e81e05-a150-456e-89f5-f54f17a0b863)

**Comment by rbong** [comment] 2024-09-02 19:21
The `minitrailspace_disable` variable is being set as soon as I can, I think the issue is on their side. Try `echo b:minitrailspace_disable` to see if it's being set, and make sure you are on `v3` or you have an autocommand to set it up.

**Comment by 231tr0n** [comment] 2024-09-02 19:33
> The `minitrailspace_disable` variable is being set as soon as I can, I think the issue is on their side. Try `echo b:minitrailspace_disable` to see if it's being set, and make sure you are on `v3` or you have an autocommand to set it up.

I get this error when I switch to branch v3 and mini.trailspace is not disabled yet probably due to the error occured.

![image](https://github.com/user-attachments/assets/5df28114-bd95-48a1-a9ee-4d78eebab853)
![image](https://github.com/user-attachments/assets/48e6279e-3cf0-46ea-831f-588285e9e5e2)

**Comment by rbong** [comment] 2024-09-02 19:43
Something else may be overwriting `b:minitrailspace_disable` in that case. The error is unrelated and won't happen until much later when the setting is already on, highlighting goes last. I will check it out when I can.

**Comment by rbong** [comment] 2024-09-02 21:13
It does appear to be a paroblem with mini.trailspace. I noticed that the issue goes away after moving to a different window. Here's the thing - Flog doesn't update in this case, it's only that a mini.trailspace autocmd is being triggered. And again, we're setting it to disabled as soon as possible.

Workaround in `init.lua`:

```lua
vim.api.nvim_create_autocmd(
  "User",
  {
    pattern = { "FlogUpdate" },
    callback = function (ev)
      require("mini.trailspace").unhighlight()
    end,
  }
)
```

I also fixed the problems that were causing your highlight errors.

Thanks again for reporting, let me know if you encounter any more errors.

**Closed by rbong** 2024-09-02 21:13 UTC

**Comment by 231tr0n** [comment] 2024-09-03 05:11
> It does appear to be a paroblem with mini.trailspace. I noticed that the issue goes away after moving to a different window. Here's the thing - Flog doesn't update in this case, it's only that a mini.trailspace autocmd is being triggered. And again, we're setting it to disabled as soon as possible.
> 
> Workaround in `init.lua`:
> 
> ```lua
> vim.api.nvim_create_autocmd(
>   "User",
>   {
>     pattern = { "FlogUpdate" },
>     callback = function (ev)
>       require("mini.trailspace").unhighlight()
>     end,
>   }
> )
> ```
> 
> I also fixed the problems that were causing your highlight errors.
> 
> Thanks again for reporting, let me know if you encounter any more errors.

@rbong sure i will go ahead with this workaround but i just have one more query.
Like after drawing the graph in the buffer running something like this should remove all trailing spaces right.
```vim
function <SID>StripTrailingWhitespaces()
  let l=line(".")
  let c=col(".")
  %s/\s\+$//e
  call cursor(l, c)
endfunction
```
Is something like this function possible to be run after the graph is drawn on the buffer. If this can be done this function should strip all trailing spaces essentially providing the best possible outcome. And this function does not dabble with the graph drawing algorithm thus providing an ideal scenario.

**Comment by rbong** [comment] 2024-09-03 05:52
Thank you for the suggestion, yes that would work I also don't want to modify the graph buffer in new ways to avoid unforeseen consequences at least until v3 is out for a while.
