### ISSUE TITLE
Everytime I press <CR> to view do a commit show, the window size gets smaller

### ISSUE THREAD

**Issue by MartyLake** [rbong/vim-flog#136] opened 2024-08-19 15:58 UTC
# reproduction steps

1. open some file versioned in a git repository
2. run :Flog to open flog
3. press <CR>
4. the commit is shown in a window split taking half the size of the full vim session
5. press <CR>

# expected

6. the commit is shown in a window split taking half the size of the full vim session

# actual

6. the commit is shown in a window split taking 75% the size of the full vim session

**Comment by rbong** [comment] 2024-08-19 16:14
Thank you for reporting this issue. I was not able to reproduce this on the newest version of Flog and Fugitive.

Do you get the same result from running `botright vertical Gsplit <hash>`, where `<hash>` is the hash of any commit in your repository?

If you do get the same result, does it happen from any window or just the Flog window? If you don't get the same result, can you please share:

* What version of vim or neovim you're using (`vim --version` or `nvim --version`)
* Your `.vimrc` or `init.lua` file

Thank you

**Comment by MartyLake** [comment] 2024-08-19 23:16
Thanks!
After failing to reproduce with a minimal vimrc, I bisected to this option
`set noequalalways`
If I remove this option from my vimrc, the bug I reported disappears.

The bug also dissapears if I put those lines
```
set noequalalways
autocmd FileType floggraph setlocal equalalways
```

**Comment by rbong** [comment] 2024-08-20 16:27
Thank you very much for narrowing down the issue.

This is trickier than it appears. `setlocal equalalways` will actually enable `equalalways` everywhere, since it is a global option. I don't want to overwrite/force this option for everyone.

The problem is caused by temporary side windows. When you run a command that can open temporary side windows, it runs the command, checks for new windows, then closes the old windows if any new ones were detected. We don't want to change this to close windows first because that would cause commands that don't open any windows to close old ones, which is unintuitive.

I have pushed a fix to manually run `wincmd =` when windows are closed. This is an alright solution when running Flog in its own tab, but I don't like that it will equalize windows even though the setting is off and that it will equalize all windows even when Flog is opened using `:Flogsplit`. I am leaving this open until I can implement a more intelligent solution.

**Comment by rbong** [comment] 2024-08-20 18:18
I've pushed a better solution, which is to lock windows only when necessary. Any window sizes untouched by new temporary windows opening is now locked before running `wincmd =`, then unlocked afterwards.

This is a *better* solution, which only equalizes necessary windows, but is not a *perfect* solution, because it does not technically respect `noequalalways` and it will resize new temporary side windows even if they're set to a certain desired size.

There are a bunch of other side effects of having "magic" temporary side windows that know when to close, so the true solution is to either make users accept that windows are magic and will not always behave as expected or to always close temporary side windows first and force users to accept that. Not happy with either solution, but I will probably change it to the latter in `v3`.

**Comment by MartyLake** [comment] 2024-08-21 01:41
I can confirm that your latest vestion fixes the issue on my side: I can set noequalalways while observing the expected behavior from vim-flog.

> `setlocal equalalways` will actually enable `equalalways` everywhere, since it is a global option. 

I didn't know that. Thanks for the tip!

**Closed** 2024-08-21 21:02 UTC
Labels: help wanted, feedback wanted

**Comment by rbong** [comment] 2024-08-26 16:59
Properly fixed in [v3](https://github.com/rbong/vim-flog/issues/135). Temporary windows will now close before running a command instead of trying to detect if new windows opened after running it.

I *think* the only side-effect is that integration with other plugins is slightly harder now, but please let me know if there are any other issues.
