### ISSUE TITLE
Issue with flog on WSL

### ISSUE THREAD

**Issue by ferdinandyb** [rbong/vim-flog#108] opened 2023-07-27 11:49 UTC
I'm trying to run flog in WSL, my setup is exactly the same as on my Ubuntu machine where things work. I'm getting this error, when trying to `:Flog`

```
Error detected while compiling function flog#cmd#Flog[19]..flog#floggraph#buf#Update[21]..flog#graph#vim#Get[14]..function flog#cmd#Flog[19]..flog#floggraph#buf#Update[21].
.flog#graph#vim#Get[10]..FlogGetVimBinGraph:
line   27:
E909: Cannot index a special variable
Press ENTER or type command to continue
```

I should be running the latest version of flog with vim 9.0. Any idea what could be going wrong? Fugitive works fine.

**Comment by rbong** [comment] 2023-07-27 13:43
Duplicate of #94 and #97 - unfortunately a bug with vim itself. Please build the latest version of Vim from source. Apologies for the inconvenience.

**Closed by rbong** 2023-07-27 13:43 UTC
