### ISSUE TITLE
Feature request: add support for File mode

### ISSUE THREAD

**Issue by giorgioprevitera** [rbong/vim-flog#1] opened 2019-03-03 22:07 UTC
Add support for File mode, similar to Gitv:

> 3.2 File mode
> File mode is opened in a preview-window above the buffer you are currently in.
> This view is tailored to act on the buffer that :Gitv! was run from, the
> "focused" file. Whilst in this mode all actions performed are specific to the
> single focused file. The browser only shows commits where the focused file
> changed.  Selecting a commit, views the focused file as it was in that commit.
> Performing a check out only checks the focused file out as it was in the
> commit. And so on.

**Comment by rbong** [comment] 2019-03-03 22:44
While everything is in place to support different modes of operation, to open up the commit in a split, and to pass in a path, I personally tended to not use Gitv in file mode for one reason or another.

So, I need your help here so I can implement this properly - what is the use case here? When do you typically use file browser mode? What features of it do you rely on? If anyone else would like to chime in as well, please do so.

**Comment by lervag** [comment] 2019-03-04 21:20
To me it seems this is "supported" in the sense that `:Flog -path=.' works similar to `:Gitv!`. At least in the sense that both will show the log for the current buffer, unless I'm somehow mistaken?

**Comment by lervag** [comment] 2019-03-04 21:48
No, sorry, that does not work as intended. I would have expected `-path=%` to work, but it does not:

```
Error detected while processing function flog#open[10]..flog#open_graph[6]..flog#i
nitialize_graph_buffer[4]..flog#populate_graph_buffer[5]..flog#parse_log_output:
line    2:
E605: Exception not caught: flog: error parsing commits: no git output
```

**Comment by lervag** [comment] 2019-03-04 21:50
I can get around it with this mapping:

```
nnoremap <silent><leader>gF :execute 'Flog -all -path=' . expand('%:t')<cr>
```

**Comment by rbong** [comment] 2019-03-04 23:22
`%` and other expansions should now work.

`:Flog -path=%`

Let me know what else you might need to replace file mode.

**Comment by lervag** [comment] 2019-03-05 16:56
Thanks, this is very nice. I've personally never used the file mode of `:Gitv` for much more than browsing the "local" commits, so I don't have any more suggestions.

**Comment by rbong** [comment] 2019-11-04 06:20
I have had a lot of time to think about this and add new things.

First, launching in visual mode now tracks history just for the selected lines. A manual range can also be passed in with `-limit` in the format accepted by the git-log `-L` argument. This, obviously, replaces line tracking mode from gitv.

Second, paths passed in with `-path` or `-limit` are now completed for `:Floggit` commands. This is not the fastest way to run commands against paths, but it is in line with what's been done regarding making commands faster so far. This, in theory, replaces all filemode specific commands from gitv.

All of the file mode features from gitv have now been replaced in a minimal sense. It's definitely not perfect, but any improvements to these replacements might come in the form of systems that aren't even specific to this issue, and I can't track the improvement of these types of changes in this issue forever, so I am going to go ahead and close this.

If there are any further suggestions to improve any features, or if there are any bugs regarding the newly implemented features, please post a new issue.

**Comment by lervag** [comment] 2019-11-04 07:40
Very good work! The visual mode feature is neat. And the file mode has worked for me as expected since March.

**Comment by AlanWarren** [comment] 2021-09-23 17:09
Hello,  I realize this issue is closed but I've come here searching for feature parity with gitv.  I've been using gitv for many years, and I'm honestly having a hard time.  :GItv! (file mode) is pretty much the only reason I used gitv, so I'll try to explain.

With gitv, I could add a commit graph in a split buffer for an indivudual file with :Gitv!.  Selecting a commit and hitting <cr> displays the file at that point in time.  It doesn't checkout the file, you just get to browse the file's contents from how it was in that commit.  You can quickly step back through a file's history and view contents using this method.  You may be thinking, why would you want to see the entire file when you can see diffs, but I'll get to that.     

The most powerful feature for me personally, is the ability to load the file in the buffer from any point in it's history, and then open a vertical diffsplit from any other commit in that file's history.  Gitv! let the user achieve this by the behavior noted above.  i.e. when you select a commit, the file is loaded into the buffer from that point in time.  You are free to diffsplit with any commit you want.  If there's an easier or more powerful way to diff invidual file history then I'd love to know how other developers are doing it.   I work in very large, and very old repos, and this is exceedingly helpful for me.  I can find exactly when pieces of code are added and then removed, etc.  

Note the vscode git lense extension can do all of these same tasks.  It allows you to view commit history for an individual file, view file contents from any specific commit, and the user can select specific commits to compare in the code editor.    

Can Flog achieve these features?  So far I'm testing out :Flogsplit -path=%<cr> but i'm only able to view commit details. How can I visually, and quickly select individual commits from a specific file's history and diff them?  

Thanks!

**Comment by TamaMcGlinn** [comment] 2021-09-24 13:03
I have two bindings that are for this use-case, although neither are quite what you ask for:

## git log this
```
nnoremap <leader>glt :Git log --patch -- %<CR>
nnoremap <leader>glT :Flog -format=%ad\ [%h]\ {%an}%d\ (%S)\ %s -all -path=%<CR>
```

The first shows a list of commits that touched the file, with the diffs folded by default ([with this separate setting](https://github.com/TamaMcGlinn/vimrc/blob/master/ftplugin/git.vim)), but does not show the git log graph. For example:

```
commit 48ed84b9b2a4998808dfcc0d78e62c5c139e6aac
Author: Tama McGlinn <t.mcglinn@gmail.com>
Date:   Fri Aug 13 14:45:23 2021 +0200

    Fugitive; fold by files

+--   2+ 0-  git.vim

commit 0e4e47184afaa8f8980892721a84b6f4383eea52
Author: Tama McGlinn <t.mcglinn@gmail.com>
Date:   Sat Aug 7 09:14:06 2021 +0200

    Fix vint errors

+--   2+ 0-  git.vim 
```

The second binding, bound to glT for me, shows the graph and commit relations, and allows me to use my flog bindings, but unfortunately each commit has a line straight down as well, so I get this sideways stacking effect. Like this:

```
┌ 2021-08-13 [48ed84b] {Tama McGlinn} (refs/heads/master) Fugitive; fold by files
│ ┌ 2021-08-07 [0e4e471] {Tama McGlinn} (refs/heads/master) Fix vint errors
│ │ ┌ 2021-08-06 [69587e0] {Tama McGlinn} (refs/heads/master) moved some stuff into vim-flog fork
│ │ │ ┌ 2021-07-14 [413563f] {Tama McGlinn} (refs/heads/master) Fix gJ when no tracking branch set
│ │ │ │ ┌ 2021-06-04 [bab8147] {Tama McGlinn} (refs/heads/master) Compare g[ g] populates qf list
│ │ │ │ │ ┌ 2021-05-25 [639c4ac] {Tama McGlinn} (refs/heads/master) flog airline integration
│ │ │ │ │ │ ┌ 2021-05-23 [63a6e09] {Tama McGlinn} (refs/heads/master) flog(menu) bindings silent
│ │ │ │ │ │ │ ┌ 2021-05-21 [f5d56d2] {Tama McGlinn} (refs/heads/master) Quickfix diffs with gd
│ │ │ │ │ │ │ ├ 2021-05-20 [5d373d7] {Tama McGlinn} (refs/heads/master) flogteamjump
│ │ │ │ │ │ │ ├ 2021-05-20 [c046b8d] {Tama McGlinn} (refs/heads/master) stuff; cycle unstaged with ]X half working
│ │ │ │ │ │ │ │ ┌ 2021-05-18 [369ca9c] {Tama McGlinn} (refs/heads/master) Add git-messenger gm
│ │ │ │ │ │ │ │ │ ┌ 2021-05-06 [8ae53dc] {Tama McGlinn} (refs/heads/master) GBrowse mapping gx
│ │ │ │ │ │ │ │ │ │ ┌ 2021-05-04 [a4c5114] {Tama McGlinn} (refs/heads/master) Dirvish ]c [c just like Signify inside file
│ │ │ │ │ │ │ │ │ │ │ ┌ 2021-05-04 [4e5e57b] {Tama McGlinn} (refs/heads/master) Merge branch 'master' of github.com:TamaMcGlinn/vimrc
│ │ │ │ │ │ │ │ │ │ │ ├─╮  
│ │ │ │ │ │ │ │ │ │ │ │ │ ┌ 2021-05-04 [6f53ba8] {Tama McGlinn} (refs/heads/master) GBrowse from flog
│ │ │ │ │ │ │ │ │ │ │ │ │ │ ┌ 2021-05-03 [ab0c870] {Tama McGlinn} (refs/heads/master) Switch worktree mapping
```

**Comment by AlanWarren** [comment] 2021-09-24 14:00
Thank you, I appreciate you sharing that.  I'll check it out. 

I found something that's pretty much the same thing as Gitv's file mode with fugitive's `:0Gclog`  I get a quickfix with the commits for the file in my buffer. Clicking them loads the file into a fugitive buffer.  I can copy the SHA with yiw and use :Gvdiffsplit SHA to diff them. 

Unfortunately it's more tedious than gitv, and doesn't really offer any benefits over it.  I'll keep an eye out for plugins that address this feature.

**Comment by rbong** [comment] 2021-10-10 22:35
I'm reopening because I've added a new feature to accommodate this workflow better and I'd like some feedback.

What I realized from the comments from @AlanWarren was that there was no amazing way to easily do stateful operations in Flog.
I've added a feature that, I hope, is fairly vim-like and robust and fills a gap left that make Flog weaker that Gitv in areas.

Previously, you could do operations between two commits if you could easily visually select them, but you couldn't select one commit and then do something with it later. You *could* use vim's builtin marking system, but that mark would become meaningless between graph buffer updates since it marks a line and not a commit.

That's why I've added **"commit marks"**.

Now, when you make a mark in a Flog buffer with `m`, it will mark the commit, not the line.

You can later use this mark in commands, which is the important part of this feature that allows Gitv-like file mode behaviour, which I will explain in the comment after this.

You can also jump to a marked commit with `'`. Since the mark persists between graph buffer updates, you will be taken directly to the commit, instead of to the line that commit was on like before.

The feedback I would like is:
* What do you think of the feature?
* Would you like to see any default keybindings for marks, and if so what?

**Comment by rbong** [comment] 2021-12-27 13:03
>I think a <plug> mapping for the examples you provide would be useful

The plugin mappings are: `<Plug>(FlogSetCommitMark)` and `<Plug>(FlogJumpToCommitMark)`.

>I believe it would be nice with a couple of special marks

I have added the following commit marks:

* `@`: the current `HEAD`
* `~` or `^`: the parent of the current `HEAD`

I went with `@` instead of `H`, because like with normal vim marks I would like to save alphabetic marks for users.

**Comment by rbong** [comment] 2022-01-01 10:27
I've now added the `'!` commit mark. This commit mark is automatically set whenever you use `%h` in a command, use `Flogsplitcommit`, or use any binding that opens a commit. It can be thought of as the "last used commit" or "last opened commit".

Hopefully this should help avoid having to set a lot of commit marks. I was trying to think of a special commit mark that covers a lot of cases, and hopefully this should be it.

You can use `%H` instead of `%h` in a command to avoid setting it.

I've also added the `d!` mapping to diff the commit under the cursor with this commit mark.

Finally, you can use `D!` to do the same, but use the `-path` command do show the diff only for the current path.

For consistency the `dp` command can now instead be used with the `DD` command. Maybe this is not the best solution as it's not very mnemonic and `D` is probably a mapping a lot of people use, but I didn't want 3-character-long diff mappings either. I will wait for feedback on this.

I think this should tie things up for file mode and general Gitv parity and what I wanted out of it.

If you have any feedback or issues with the new features, please open a new issue.

**Closed by rbong** 2022-01-01 10:27 UTC
